import { actions } from '../constants/actions';
import { colors } from '../constants/colors';

export const core = {
    parent: '',
    words: [
        { y: 0, x: 0, word: "the", icon: "", emoji: "the", bg: colors.lightblue },
        { y: 0, x: 1, word: "of", icon: "", emoji: "of" },
        { y: 0, x: 2, word: "to", icon: "", emoji: "🛫" },
        { y: 0, x: 3, word: "and", icon: "", emoji: "&" },
        { y: 0, x: 4, word: "a", icon: "", emoji: "a", bg: colors.lightblue, expand: ["an"] },
        { y: 0, x: 5, word: "in", icon: "my_location", emoji: "" },
        { y: 0, x: 6, word: "is", icon: "", emoji: "⏳" },
        { y: 0, x: 7, word: "it", icon: "", emoji: "it", bg: colors.green, expand: ["its"] },
        { y: 0, x: 8, word: "you", icon: "", emoji: "U", bg: colors.green, expand: ["your", "yours"] },
        { y: 0, x: 9, word: "she", icon: "", emoji: "♀️", bg: colors.green, expand: ["her", "hers"] },
        { y: 0, x: 10, word: "be", icon: "", emoji: "🐝" },
        { y: 1, x: 0,  word: "was", icon: "", emoji: "⌛" },
        { y: 1, x: 1,  word: "for", icon: "", emoji: "📦" },
        { y: 1, x: 2,  word: "on", icon: "", emoji: "🔛" },
        { y: 1, x: 3,  word: "are", icon: "", emoji: ".✊" },
        { y: 1, x: 4,  word: "with", icon: "supervised_user_circle", emoji: "" },
        { y: 1, x: 5,  word: "as", icon: "", emoji: "as" },
        { y: 1, x: 6,  word: "I", icon: "", emoji: "I", bg: colors.green, expand: ["me", "my", "mine", "I am"] },
        { y: 1, x: 7,  word: "they", icon: "", emoji: "👩‍👧‍👧", bg: colors.green, expand: ["them", "their", "theirs"] },
        { y: 1, x: 8,  word: "he", icon: "", emoji: "♂️", bg: colors.green, expand: ["him", "his"] },
        { y: 1, x: 9,  word: "at", icon: "", emoji: "@" },
        { y: 1, x: 10, word: "go", icon: "", emoji: "🚀", expand: ["gone", "going", "went"] },
        { y: 2, x: 0,  word: "this", icon: "", emoji: "↘️" },
        { y: 2, x: 1,  word: "have", icon: "", emoji: "🙌", expand: ["has", "had", "having"] },
        { y: 2, x: 2,  word: "from", icon: "", emoji: "✉️" },
        { y: 2, x: 3,  word: "or", icon: "", emoji: "or" },
        { y: 2, x: 4,  word: "by", icon: "", emoji: "by" },
        { y: 2, x: 5,  word: "not", icon: "", emoji: "🚫" },
        { y: 2, x: 6,  word: "but", icon: "toll", emoji: "" },
        { y: 2, x: 7,  word: "some", icon: "", emoji: "👨‍👩‍👧‍👦" },
        { y: 2, x: 8,  word: "what", icon: "", emoji: "😕" },
        { y: 2, x: 9,  word: "there", icon: "", emoji: "🗺️" },
        { y: 2, x: 10, word: "we", icon: "", emoji: "👨‍👩‍👧‍👦", expand: ["us", "our", "ours"] },
        { y: 3, x: 0,  word: "can", icon: "", emoji: "🥫" },
        { y: 3, x: 1,  word: "out", icon: "", emoji: "🚪" },
        { y: 3, x: 2,  word: "other", icon: "shuffle", emoji: "" },
        { y: 3, x: 3,  word: "were", icon: "", emoji: ".⌛" },
        { y: 3, x: 4,  word: "all", icon: "", emoji: "🔣" },
        { y: 3, x: 5,  word: "when", icon: "slow_motion_video", emoji: "" },
        { y: 3, x: 6,  word: "up", icon: "", emoji: "👆" },
        { y: 3, x: 7,  word: "use", icon: "", emoji: "💪", expand: ["used", "using"] },
        { y: 3, x: 8,  word: "no", icon: "", emoji: "🙅" },
        { y: 3, x: 9,  word: "how", icon: "", emoji: "❓" },
        { y: 3, x: 10, word: "say", icon: "", emoji: "🗣️", expand: ["said", "saying"] },
        { y: 4, x: 0,  word: "that", icon: "", emoji: "↗️" },
        { y: 4, x: 1,  word: "each", icon: "room", emoji: "" },
        { y: 4, x: 2,  word: "which", icon: "call_split", emoji: "" },
        { y: 4, x: 3,  word: "do", icon: "", emoji: "📝", expand: ["done", "doing"] },
        { y: 4, x: 4,  word: "time", icon: "", emoji: "⏲️", expand: ["timed", "timing"] },
        { y: 4, x: 5,  word: "if", icon: "compare_arrows", emoji: "" },
        { y: 4, x: 6,  word: "will", icon: "", emoji: "🔋" },
        { y: 4, x: 7,  word: "way", icon: "navigation", emoji: "" },
        { y: 4, x: 8,  word: "about", icon: "art_track", emoji: "" },
        { y: 4, x: 9,  word: "many", icon: "view_module", emoji: "" },
        { y: 4, x: 10, word: "then", icon: "import_export", emoji: "" },
        { y: 5, x: 0,  word: "would", icon: "trending_up", emoji: "" },
        { y: 5, x: 1,  word: "more", icon: "more", emoji: "" },
        { y: 5, x: 2,  word: "like", icon: "", emoji: "👍" },
        { y: 5, x: 3,  word: "so", icon: "", emoji: "so" },
        { y: 5, x: 4,  word: "these", icon: "settings_ethernet", emoji: "" },
        { y: 5, x: 5,  word: "long", icon: "", emoji: "" },
        { y: 5, x: 6,  word: "make", icon: "", emoji: "🧱", expand: ["made", "making"] },
        { y: 5, x: 7,  word: "yes", icon: "", emoji: "👌" },
        { y: 5, x: 8,  word: "see", icon: "", emoji: "👀", expand: ["saw", "seeing", "seen"] },
        { y: 5, x: 9,  word: "want", icon: "", emoji: "🤲", expand: ["wanted", "wanting"] },
        { y: 5, x: 10, word: "look", icon: "", emoji: "👁️‍🗨️", expand: ["looked", "looking"] },
        // bottom row are for navigating to a new page
        { y: 6, x: 0,  word: "core2", icon: "more_horiz", action: "page" },
        { y: 6, x: 1,  word: "food", icon: "local_dining", action: "page" },
        { y: 6, x: 2,  word: "home", icon: "home", action: "page" },
        { y: 6, x: 3,  word: "activity", icon: "local_activity", action: "page" }, // sports, games
        { y: 6, x: 4,  word: "routine", icon: "repeat", action: "page" }, // brush teeth, dress, bedtime, bathe
        { y: 6, x: 5,  word: "drink", icon: "local_drink", action: "page" }, // water, juice, milk
        { y: 6, x: 6,  word: "places", icon: "public", action: "page" }, // restroom, stores
        { y: 6, x: 7,  word: "people", icon: "people_alt", action: "page" }, // woman, girl, man, boy, baby, professions, etc
        { y: 6, x: 8,  word: "things", icon: "dynamic_feed", action: "page" },
        { y: 6, x: 9,  word: "myself", icon: "fingerprint", action: "page" }, // body, body parts, emotions, self image
        { y: 6, x: 10, word: "numbers", icon: "format_list_numbered", action: "page" },
    ]
};