import { actions } from '../constants/actions';
import { colors } from '../constants/colors';

export const numbers = {
    parent: 'core',
    words: [
        { y: 0, x: 0, word: "number", icon: "", emoji: "🔢" },
        { y: 0, x: 1, word: "", icon: "", emoji: "" },
        { y: 0, x: 2, word: "digit", icon: "", emoji: "" },
        { y: 0, x: 3, word: "", icon: "", emoji: "" },
        { y: 0, x: 4, word: "single", icon: "", emoji: "" },
        { y: 0, x: 5, word: "", icon: "", emoji: "" },
        { y: 0, x: 6, word: "count", icon: "format_list_numbered", emoji: "", expand: ["counted", "counting"] },
        { y: 0, x: 7, word: "", icon: "", emoji: "" },
        { y: 0, x: 8, word: "", icon: "", emoji: "" },
        { y: 0, x: 9, word: "", icon: "", emoji: "" },
        { y: 0, x: 10, word: "", icon: "", emoji: "" },
        { y: 1, x: 0,  word: "zero", icon: "", emoji: "0" },
        { y: 1, x: 1,  word: "one", icon: "", emoji: "1" },
        { y: 1, x: 2,  word: "two", icon: "", emoji: "2" },
        { y: 1, x: 3,  word: "three", icon: "", emoji: "3" },
        { y: 1, x: 4,  word: "four", icon: "", emoji: "4" },
        { y: 1, x: 5,  word: "five", icon: "", emoji: "5" },
        { y: 1, x: 6,  word: "six", icon: "", emoji: "6" },
        { y: 1, x: 7,  word: "seven", icon: "", emoji: "7" },
        { y: 1, x: 8,  word: "eight", icon: "", emoji: "8" },
        { y: 1, x: 9,  word: "nine", icon: "", emoji: "9" },
        { y: 1, x: 10, word: "", icon: "", emoji: "" },
        { y: 2, x: 0,  word: "ten", icon: "", emoji: "10" },
        { y: 2, x: 1,  word: "eleven", icon: "", emoji: "11" },
        { y: 2, x: 2,  word: "twelve", icon: "", emoji: "12" },
        { y: 2, x: 3,  word: "thirteen", icon: "", emoji: "13" },
        { y: 2, x: 4,  word: "fourteen", icon: "", emoji: "14" },
        { y: 2, x: 5,  word: "fifteen", icon: "", emoji: "15" },
        { y: 2, x: 6,  word: "sixteen", icon: "", emoji: "16" },
        { y: 2, x: 7,  word: "seventeen", icon: "", emoji: "17" },
        { y: 2, x: 8,  word: "eighteen", icon: "", emoji: "18" },
        { y: 2, x: 9,  word: "nineteen", icon: "", emoji: "19" },
        { y: 2, x: 10, word: "", icon: "", emoji: "" },
        { y: 3, x: 0,  word: "twenty", icon: "", emoji: "20" },
        { y: 3, x: 1,  word: "thirty", icon: "", emoji: "30" },
        { y: 3, x: 2,  word: "forty", icon: "", emoji: "40" },
        { y: 3, x: 3,  word: "fifty", icon: "", emoji: "50" },
        { y: 3, x: 4,  word: "sixty", icon: "", emoji: "60" },
        { y: 3, x: 5,  word: "seventy", icon: "", emoji: "70" },
        { y: 3, x: 6,  word: "eighty", icon: "", emoji: "80" },
        { y: 3, x: 7,  word: "ninety", icon: "", emoji: "90" },
        { y: 3, x: 8,  word: "", icon: "", emoji: "" },
        { y: 3, x: 9,  word: "", icon: "", emoji: "" },
        { y: 3, x: 10, word: "", icon: "", emoji: "" },
        { y: 4, x: 0,  word: "hundred", icon: "", emoji: "💯" },
        { y: 4, x: 1,  word: "", icon: "", emoji: "" },
        { y: 4, x: 2,  word: "thousand", icon: "", emoji: "" },
        { y: 4, x: 3,  word: "", icon: "", emoji: "" },
        { y: 4, x: 4,  word: "million", icon: "", emoji: "" },
        { y: 4, x: 5,  word: "", icon: "", emoji: "" },
        { y: 4, x: 6,  word: "billion", icon: "", emoji: "" },
        { y: 4, x: 7,  word: "", icon: "", emoji: "" },
        { y: 4, x: 8,  word: "trillion", icon: "", emoji: "" },
        { y: 4, x: 9,  word: "", icon: "", emoji: "" },
        { y: 4, x: 10, word: "", icon: "", emoji: "" },
        { y: 5, x: 0,  word: "once", icon: "", emoji: "☝️" },
        { y: 5, x: 1,  word: "", icon: "", emoji: "" },
        { y: 5, x: 2,  word: "twice", icon: "", emoji: "✌️" },
        { y: 5, x: 3,  word: "", icon: "", emoji: "" },
        { y: 5, x: 4,  word: "", icon: "", emoji: "" },
        { y: 5, x: 5,  word: "", icon: "", emoji: "" },
        { y: 5, x: 6,  word: "", icon: "", emoji: "" },
        { y: 5, x: 7,  word: "", icon: "", emoji: "" },
        { y: 5, x: 8,  word: "statistic", icon: "", emoji: "" },
        { y: 5, x: 9,  word: "", icon: "", emoji: "" },
        { y: 5, x: 10, word: "", icon: "", emoji: "" },
        { y: 6, x: 0,  word: "core", icon: "more_horiz", emoji: "", action: "page" },
        { y: 6, x: 1,  word: "math", icon: "", emoji: "", action: "page" },
        { y: 6, x: 2,  word: "", icon: "", emoji: "", action: "page" },
        { y: 6, x: 3,  word: "", icon: "", emoji: "", action: "page" },
        { y: 6, x: 4,  word: "", icon: "", emoji: "", action: "page" },
        { y: 6, x: 5,  word: "", icon: "", emoji: "", action: "page" },
        { y: 6, x: 6,  word: "", icon: "", emoji: "", action: "page" },
        { y: 6, x: 7,  word: "", icon: "", emoji: "", action: "page" },
        { y: 6, x: 8,  word: "", icon: "", emoji: "", action: "page" },
        { y: 6, x: 9,  word: "", icon: "", emoji: "", action: "page" },
        { y: 6, x: 10, word: "", icon: "", emoji: "", action: "page" },
    ]
};