import { actions } from '../constants/actions';
import { colors } from '../constants/colors';

export const routine = {
    parent: 'core',
    words: [
        { y: 0, x: 0, word: "routine", icon: "", emoji: "" },
        { y: 0, x: 1, word: "", icon: "", emoji: "" },
        { y: 0, x: 2, word: "", icon: "", emoji: "" },
        { y: 0, x: 3, word: "before", icon: "", emoji: "" },
        { y: 0, x: 4, word: "", icon: "", emoji: "" },
        { y: 0, x: 5, word: "", icon: "", emoji: "" },
        { y: 0, x: 6, word: "after", icon: "", emoji: "" },
        { y: 0, x: 7, word: "", icon: "", emoji: "" },
        { y: 0, x: 8, word: "", icon: "", emoji: "" },
        { y: 0, x: 9, word: "repeat", icon: "", emoji: "" },
        { y: 0, x: 10, word: "", icon: "", emoji: "" },
        { y: 1, x: 0,  word: "", icon: "", emoji: "" },
        { y: 1, x: 1,  word: "", icon: "", emoji: "" },
        { y: 1, x: 2,  word: "", icon: "", emoji: "" },
        { y: 1, x: 3,  word: "", icon: "", emoji: "" },
        { y: 1, x: 4,  word: "", icon: "", emoji: "" },
        { y: 1, x: 5,  word: "", icon: "", emoji: "" },
        { y: 1, x: 6,  word: "", icon: "", emoji: "" },
        { y: 1, x: 7,  word: "", icon: "", emoji: "" },
        { y: 1, x: 8,  word: "", icon: "", emoji: "" },
        { y: 1, x: 9,  word: "", icon: "", emoji: "" },
        { y: 1, x: 10, word: "", icon: "", emoji: "" },
        { y: 2, x: 0,  word: "", icon: "", emoji: "" },
        { y: 2, x: 1,  word: "again", icon: "", emoji: "" },
        { y: 2, x: 2,  word: "", icon: "", emoji: "" },
        { y: 2, x: 3,  word: "", icon: "", emoji: "" },
        { y: 2, x: 4,  word: "", icon: "", emoji: "" },
        { y: 2, x: 5,  word: "", icon: "", emoji: "" },
        { y: 2, x: 6,  word: "", icon: "", emoji: "" },
        { y: 2, x: 7,  word: "", icon: "", emoji: "" },
        { y: 2, x: 8,  word: "", icon: "", emoji: "" },
        { y: 2, x: 9,  word: "", icon: "", emoji: "" },
        { y: 2, x: 10, word: "", icon: "", emoji: "" },
        { y: 3, x: 0,  word: "", icon: "", emoji: "" },
        { y: 3, x: 1,  word: "", icon: "", emoji: "" },
        { y: 3, x: 2,  word: "", icon: "", emoji: "" },
        { y: 3, x: 3,  word: "", icon: "", emoji: "" },
        { y: 3, x: 4,  word: "", icon: "", emoji: "" },
        { y: 3, x: 5,  word: "", icon: "", emoji: "" },
        { y: 3, x: 6,  word: "", icon: "", emoji: "" },
        { y: 3, x: 7,  word: "", icon: "", emoji: "" },
        { y: 3, x: 8,  word: "", icon: "", emoji: "" },
        { y: 3, x: 9,  word: "", icon: "", emoji: "" },
        { y: 3, x: 10, word: "", icon: "", emoji: "" },
        { y: 4, x: 0,  word: "", icon: "", emoji: "" },
        { y: 4, x: 1,  word: "", icon: "", emoji: "" },
        { y: 4, x: 2,  word: "", icon: "", emoji: "" },
        { y: 4, x: 3,  word: "", icon: "", emoji: "" },
        { y: 4, x: 4,  word: "", icon: "", emoji: "" },
        { y: 4, x: 5,  word: "", icon: "", emoji: "" },
        { y: 4, x: 6,  word: "", icon: "", emoji: "" },
        { y: 4, x: 7,  word: "", icon: "", emoji: "" },
        { y: 4, x: 8,  word: "", icon: "", emoji: "" },
        { y: 4, x: 9,  word: "", icon: "", emoji: "" },
        { y: 4, x: 10, word: "", icon: "", emoji: "" },
        { y: 5, x: 0,  word: "", icon: "", emoji: "" },
        { y: 5, x: 1,  word: "", icon: "", emoji: "" },
        { y: 5, x: 2,  word: "", icon: "", emoji: "" },
        { y: 5, x: 3,  word: "", icon: "", emoji: "" },
        { y: 5, x: 4,  word: "", icon: "", emoji: "" },
        { y: 5, x: 5,  word: "", icon: "", emoji: "" },
        { y: 5, x: 6,  word: "", icon: "", emoji: "" },
        { y: 5, x: 7,  word: "", icon: "", emoji: "" },
        { y: 5, x: 8,  word: "", icon: "", emoji: "" },
        { y: 5, x: 9,  word: "", icon: "", emoji: "" },
        { y: 5, x: 10, word: "", icon: "", emoji: "" },
        { y: 6, x: 0,  word: "core", icon: "more_horiz", emoji: "", action: "page" },
        { y: 6, x: 1,  word: "", icon: "", emoji: "", action: "page" },
        { y: 6, x: 2,  word: "", icon: "", emoji: "", action: "page" },
        { y: 6, x: 3,  word: "", icon: "", emoji: "", action: "page" },
        { y: 6, x: 4,  word: "", icon: "", emoji: "", action: "page" },
        { y: 6, x: 5,  word: "", icon: "", emoji: "", action: "page" },
        { y: 6, x: 6,  word: "", icon: "", emoji: "", action: "page" },
        { y: 6, x: 7,  word: "", icon: "", emoji: "", action: "page" },
        { y: 6, x: 8,  word: "", icon: "", emoji: "", action: "page" },
        { y: 6, x: 9,  word: "", icon: "", emoji: "", action: "page" },
        { y: 6, x: 10, word: "", icon: "", emoji: "", action: "page" },
    ]
};