import { actions } from '../constants/actions';
import { colors } from '../constants/colors';
import { back } from '../constants/keyGrid';

export const fruit = {
    parent: 'eat',
    words: [
        back, // { y: 0, x: 0, back is constant on all sub-pages },
        { y: 0, x: 1, word: "fruit", icon: "", emoji: "🍏🍍", bg: colors.orange },
        { y: 0, x: 2, word: "", icon: "", emoji: "" },
        { y: 0, x: 3, word: "apple", icon: "", emoji: "🍎" },
        { y: 0, x: 4, word: "", icon: "", emoji: "" },
        { y: 0, x: 5, word: "banana", icon: "", emoji: "🍌" },
        { y: 0, x: 6, word: "", icon: "", emoji: "" },
        { y: 0, x: 7, word: "grapes", icon: "", emoji: "🍇" },
        { y: 0, x: 8, word: "", icon: "", emoji: "" },
        { y: 0, x: 9, word: "pear", icon: "", emoji: "🍐" },
        { y: 0, x: 10, word: "", icon: "", emoji: "" },
        { y: 0, x: 11, word: "melon", icon: "", emoji: "🍈" },
        { y: 1, x: 0,  word: "", icon: "", emoji: "" },
        { y: 1, x: 1,  word: "", icon: "", emoji: "" },
        { y: 1, x: 2,  word: "", icon: "", emoji: "" },
        { y: 1, x: 3,  word: "", icon: "", emoji: "" },
        { y: 1, x: 4,  word: "", icon: "", emoji: "" },
        { y: 1, x: 5,  word: "", icon: "", emoji: "" },
        { y: 1, x: 6,  word: "", icon: "", emoji: "" },
        { y: 1, x: 7,  word: "", icon: "", emoji: "" },
        { y: 1, x: 8,  word: "", icon: "", emoji: "" },
        { y: 1, x: 9,  word: "", icon: "", emoji: "" },
        { y: 1, x: 10, word: "", icon: "", emoji: "" },
        { y: 1, x: 11, word: "", icon: "", emoji: "" },
        { y: 2, x: 0,  word: "berry", icon: "", emoji: "🍓" },
        { y: 2, x: 1,  word: "", icon: "", emoji: "" },
        { y: 2, x: 2,  word: "strawberry", icon: "", emoji: "🍓" },
        { y: 2, x: 3,  word: "", icon: "", emoji: "" },
        { y: 2, x: 4,  word: "cherry", icon: "", emoji: "🍒" },
        { y: 2, x: 5,  word: "", icon: "", emoji: "" },
        { y: 2, x: 6,  word: "lemon", icon: "", emoji: "🍋" },
        { y: 2, x: 7,  word: "", icon: "", emoji: "" },
        { y: 2, x: 8,  word: "lime", icon: "", emoji: "🍋" },
        { y: 2, x: 9,  word: "", icon: "", emoji: "" },
        { y: 2, x: 10, word: "peach", icon: "", emoji: "🍑" },
        { y: 2, x: 11, word: "", icon: "", emoji: "" },
        { y: 3, x: 0,  word: "", icon: "", emoji: "" },
        { y: 3, x: 1,  word: "", icon: "", emoji: "" },
        { y: 3, x: 2,  word: "", icon: "", emoji: "" },
        { y: 3, x: 3,  word: "", icon: "", emoji: "" },
        { y: 3, x: 4,  word: "", icon: "", emoji: "" },
        { y: 3, x: 5,  word: "", icon: "", emoji: "" },
        { y: 3, x: 6,  word: "", icon: "", emoji: "" },
        { y: 3, x: 7,  word: "", icon: "", emoji: "" },
        { y: 3, x: 8,  word: "", icon: "", emoji: "" },
        { y: 3, x: 9,  word: "", icon: "", emoji: "" },
        { y: 3, x: 10, word: "", icon: "", emoji: "" },
        { y: 3, x: 11, word: "", icon: "", emoji: "" },
        { y: 4, x: 0,  word: "", icon: "", emoji: "" },
        { y: 4, x: 1,  word: "pineapple", icon: "", emoji: "🍍" },
        { y: 4, x: 2,  word: "", icon: "", emoji: "" },
        { y: 4, x: 3,  word: "plum", icon: "", emoji: "🍑" },
        { y: 4, x: 4,  word: "", icon: "", emoji: "" },
        { y: 4, x: 5,  word: "pumpkin", icon: "", emoji: "🎃" },
        { y: 4, x: 6,  word: "", icon: "", emoji: "" },
        { y: 4, x: 7,  word: "kiwi", icon: "", emoji: "🥝" },
        { y: 4, x: 8,  word: "", icon: "", emoji: "" },
        { y: 4, x: 9,  word: "tomato", icon: "", emoji: "🍅" },
        { y: 4, x: 10, word: "", icon: "", emoji: "" },
        { y: 4, x: 11, word: "avocado", icon: "", emoji: "🥑" },
        { y: 5, x: 0,  word: "", icon: "", emoji: "" },
        { y: 5, x: 1,  word: "", icon: "", emoji: "" },
        { y: 5, x: 2,  word: "", icon: "", emoji: "" },
        { y: 5, x: 3,  word: "", icon: "", emoji: "" },
        { y: 5, x: 4,  word: "", icon: "", emoji: "" },
        { y: 5, x: 5,  word: "", icon: "", emoji: "" },
        { y: 5, x: 6,  word: "", icon: "", emoji: "" },
        { y: 5, x: 7,  word: "", icon: "", emoji: "" },
        { y: 5, x: 8,  word: "", icon: "", emoji: "" },
        { y: 5, x: 9,  word: "", icon: "", emoji: "" },
        { y: 5, x: 10, word: "", icon: "", emoji: "" },
        { y: 5, x: 11, word: "", icon: "", emoji: "" },
        // { y: 6, x: 0, clear }, is a constant
        { y: 6, x: 1,  word: "", icon: "", emoji: "" },
        { y: 6, x: 2,  word: "", icon: "", emoji: "" },
        { y: 6, x: 3,  word: "", icon: "", emoji: "" },
        { y: 6, x: 4,  word: "", icon: "", emoji: "" },
        { y: 6, x: 5,  word: "", icon: "", emoji: "" },
        { y: 6, x: 6,  word: "", icon: "", emoji: "" },
        { y: 6, x: 7,  word: "", icon: "", emoji: "" },
        { y: 6, x: 8,  word: "", icon: "", emoji: "" },
        { y: 6, x: 9,  word: "", icon: "", emoji: ""  },
        { y: 6, x: 10, word: "", icon: "", emoji: "" },
        { y: 6, x: 11, word: "", icon: "", emoji: "" }
    ]
};