import { actions } from '../constants/actions';
import { colors } from '../constants/colors';

export const core = {
    parent: '',
    words: [
        { y: 0, x: 0, word: "finished", icon: "", emoji: "🏁" },
        { y: 0, x: 1, word: "mine", icon: "", emoji: "⛏️", bg: colors.lightblue },
        { y: 0, x: 2, word: "little", icon: "", emoji: "🤏" },
        { y: 0, x: 3, word: "up", icon: "", emoji: "👆" },
        { y: 0, x: 4, word: "yes", icon: "", emoji: "👌" },
        { y: 0, x: 5, word: "good", icon: "", emoji: "😇" },
        { y: 0, x: 6, word: "some", icon: "", emoji: "👨‍👩‍👧‍👦" },
        { y: 0, x: 7, word: "no", icon: "", emoji: "🙅" },
        { y: 0, x: 8, word: "down", icon: "", emoji: "👇" },
        { y: 0, x: 9, word: "out", icon: "", emoji: "🚪" },
        { y: 0, x: 10, word: "off", icon: "", emoji: "😵" },
        { y: 0, x: 11, word: "bad", icon: "", emoji: "👿" },
        { y: 1, x: 0, word: "me", icon: "", emoji: "🤭", bg: colors.lightyellow },
        { y: 1, x: 1, word: "my", icon: "", emoji: "🤗", bg: colors.lightyellow },
        { y: 1, x: 2, word: "wear", icon: "", emoji: "😎" },
        { y: 1, x: 3, word: "am", icon: "", emoji: "✊" },
        { y: 1, x: 4, word: "please", icon: "", emoji: "🙏" },
        { y: 1, x: 5, word: "that", icon: "", emoji: "↗️" },
        { y: 1, x: 6, word: "and", icon: "", emoji: "&" },
        { y: 1, x: 7, word: "in", icon: "", emoji: "⭕" },
        { y: 1, x: 8, word: "what", icon: "", emoji: "😕" },
        { y: 1, x: 9, word: "a", icon: "", emoji: "a", bg: colors.orange },
        { y: 1, x: 10, word: "+s", icon: "", emoji: "+s", action: actions.pluralize },
        { y: 1, x: 11, word: "there", icon: "", emoji: "🗺️" },
        { y: 2, x: 0, word: "I", icon: "", emoji: "I", bg: colors.lightyellow },
        { y: 2, x: 1, word: "we", icon: "", emoji: "👨‍👩‍👧‍👦", bg: colors.lightyellow },
        { y: 2, x: 2, word: "are", icon: "", emoji: ".✊", bg: colors.green },
        { y: 2, x: 3, word: "is", icon: "", emoji: "⏳", bg: colors.lightgreen },
        { y: 2, x: 4, word: "were", icon: "", emoji: ".⌛", bg: colors.lightgreen },
        { y: 2, x: 5, word: "was", icon: "", emoji: "⌛", bg: colors.lightgreen },
        { y: 2, x: 6, word: "on", icon: "", emoji: "🔛", bg: colors.lightgreen },
        { y: 2, x: 7, word: "to", icon: "", emoji: "🛫", bg: colors.lightgreen },
        { y: 2, x: 8, word: "QWERTY", icon: "", emoji: "⌨️", bg: colors.lightblue, action: actions.keyboard },
        { y: 2, x: 9, word: "an", icon: "", emoji: "an", bg: colors.lightblue },
        { y: 2, x: 10, word: "the", icon: "", emoji: "the", bg: colors.lightblue },
        { y: 2, x: 11, word: "end", icon: "", emoji: "🔚" },
        { y: 3, x: 0, word: "you", icon: "", emoji: "U", bg: colors.lightyellow },
        { y: 3, x: 1, word: "they", icon: "", emoji: "👩‍👧‍👧", bg: colors.lightyellow },
        { y: 3, x: 2, word: "new", icon: "", emoji: "👶" },
        { y: 3, x: 3, word: "play", icon: "", emoji: "▶️" },
        { y: 3, x: 4, word: "like", icon: "", emoji: "👍" },
        { y: 3, x: 5, word: "work", icon: "", emoji: "🛠️" },
        { y: 3, x: 6, word: "have", icon: "", emoji: "🙌" },
        { y: 3, x: 7, word: "feel", icon: "", emoji: "😌" },
        { y: 3, x: 8, word: "read", icon: "", emoji: "📖" },
        { y: 3, x: 9, word: "more", icon: "", emoji: "🧮" },
        { y: 3, x: 10, word: "fast", icon: "", emoji: "💨" },
        { y: 3, x: 11, word: "stop", icon: "", emoji: "🛑" },
        { y: 4, x: 0, word: "it", icon: "", emoji: "it", bg: colors.lightyellow },
        { y: 4, x: 1, word: "he", icon: "", emoji: "♂️", bg: colors.lightyellow },
        { y: 4, x: 2, word: "want", icon: "", emoji: "🤲" },
        { y: 4, x: 3, word: "all", icon: "", emoji: "🔣" },
        { y: 4, x: 4, word: "come", icon: "", emoji: "🥳" },
        { y: 4, x: 5, word: "time", icon: "", emoji: "⏲️" },
        { y: 4, x: 6, word: "do", icon: "", emoji: "📝" },
        { y: 4, x: 7, word: "go", icon: "", emoji: "🚀" },
        { y: 4, x: 8, word: "get", icon: "", emoji: "📦" },
        { y: 4, x: 9, word: "big", icon: "", emoji: "▪️⬛" },
        { y: 4, x: 10, word: "color", icon: "", emoji: "🌈" },
        { y: 4, x: 11, word: "help", icon: "", emoji: "❓" },
        { y: 5, x: 0, word: "she", icon: "", emoji: "♀️", bg: colors.lightyellow },
        { y: 5, x: 1, word: "look", icon: "", emoji: "👀" },
        { y: 5, x: 2, word: "slow", icon: "", emoji: "🦥" },
        { y: 5, x: 3, word: "hear", icon: "", emoji: "👂" },
        { y: 5, x: 4, word: "think", icon: "", emoji: "💭" },
        { y: 5, x: 5, word: "right", icon: "", emoji: "👉" },
        { y: 5, x: 6, word: "said", icon: "", emoji: "🗣️" },
        { y: 5, x: 7, word: "live", icon: "", emoji: "🏠" },
        { y: 5, x: 8, word: "love", icon: "", emoji: "😍" },
        { y: 5, x: 9, word: "follow", icon: "", emoji: "📇" },
        { y: 5, x: 10, word: "ride", icon: "", emoji: "🎢" },
        { y: 5, x: 11, word: "put", icon: "", emoji: "🚮" },
        // { y: 6, x: 0, clear }, is a constant
        { y: 6, x: 1, word: "not", icon: "", emoji: "🚫" },
        { y: 6, x: 2, word: "talk", icon: "", emoji: "🦜" },
        { y: 6, x: 3, word: "sit", icon: "", emoji: "💺" },
        { y: 6, x: 4, word: "eat", icon: "", emoji: "🍽️", action: actions.page },
        { y: 6, x: 5, word: "find", icon: "", emoji: "🔍" },
        { y: 6, x: 6, word: "make", icon: "", emoji: "🧱" },
        { y: 6, x: 7, word: "need", icon: "", emoji: "🧠" },
        { y: 6, x: 8, word: "drink", icon: "", emoji: "🥛" },
        { y: 6, x: 9, word: "watch", icon: "", emoji: "⌚" },
        { y: 6, x: 10, word: "turn", icon: "", emoji: "🎛️" },
        { y: 6, x: 11, word: "sleep", icon: "", emoji: "😴" }
    ]
};
