import { actions } from '../constants/actions';
import { colors } from '../constants/colors';
import { back } from '../constants/keyGrid';

export const eat = {
    parent: 'core',
    words: [
        back,
        { y: 0, x: 1, word: "asian", icon: "", emoji: "🤩", bg: colors.lightblue },
        { y: 0, x: 2, word: "condiment", icon: "", emoji: "🤩", bg: colors.lightblue },
        { y: 0, x: 3, word: "dairy", icon: "", emoji: "🤩", bg: colors.lightblue },
        { y: 0, x: 4, word: "fruit", icon: "", emoji: "🍏🍍", bg: colors.lightblue, action: actions.page },
        { y: 0, x: 5, word: "italian", icon: "", emoji: "🤩", bg: colors.lightblue },
        { y: 0, x: 6, word: "meals", icon: "", emoji: "🤩", bg: colors.lightblue },
        { y: 0, x: 7, word: "protein", icon: "", emoji: "🤩", bg: colors.lightblue },
        { y: 0, x: 8, word: "mexican", icon: "", emoji: "🤩", bg: colors.lightblue },
        { y: 0, x: 9, word: "snacks", icon: "", emoji: "🤩", bg: colors.lightblue },
        { y: 0, x: 10, word: "veggies", icon: "", emoji: "🤩", bg: colors.lightblue },
        { y: 0, x: 11, word: "", icon: "", emoji: "" },
        { y: 1, x: 0,  word: "", icon: "", emoji: "" },
        { y: 1, x: 1,  word: "", icon: "", emoji: "" },
        { y: 1, x: 2,  word: "", icon: "", emoji: "" },
        { y: 1, x: 3,  word: "", icon: "", emoji: "" },
        { y: 1, x: 4,  word: "", icon: "", emoji: "" },
        { y: 1, x: 5,  word: "", icon: "", emoji: "" },
        { y: 1, x: 6,  word: "", icon: "", emoji: "" },
        { y: 1, x: 7,  word: "", icon: "", emoji: "" },
        { y: 1, x: 8,  word: "", icon: "", emoji: "" },
        { y: 1, x: 9,  word: "food", icon: "", emoji: "🤩", bg: colors.orange },
        { y: 1, x: 10, word: "foods", icon: "", emoji: "🤩", bg: colors.orange },
        { y: 1, x: 11, word: "hungrily", icon: "", emoji: "🤩" },
        { y: 2, x: 0,  word: "", icon: "", emoji: "" },
        { y: 2, x: 1,  word: "", icon: "", emoji: "" },
        { y: 2, x: 2,  word: "eat", icon: "", emoji: "🤩", bg: colors.green },
        { y: 2, x: 3,  word: "eats", icon: "", emoji: "🤩", bg: colors.lightgreen },
        { y: 2, x: 4,  word: "eating", icon: "", emoji: "🤩", bg: colors.lightgreen },
        { y: 2, x: 5,  word: "ate", icon: "", emoji: "🤩", bg: colors.lightgreen },
        { y: 2, x: 6,  word: "eaten", icon: "", emoji: "🤩", bg: colors.lightgreen },
        { y: 2, x: 7,  word: "to eat", icon: "", emoji: "🤩", bg: colors.lightgreen },
        { y: 2, x: 8,  word: "hungry", icon: "", emoji: "🤩", bg: colors.lightblue },
        { y: 2, x: 9,  word: "hungrier", icon: "", emoji: "🤩", bg: colors.lightblue },
        { y: 2, x: 10, word: "hungriest", icon: "", emoji: "🤩", bg: colors.lightblue },
        { y: 2, x: 11, word: "anywhere", icon: "", emoji: "🤩" },
        { y: 3, x: 0,  word: "", icon: "", emoji: "" },
        { y: 3, x: 1,  word: "", icon: "", emoji: "" },
        { y: 3, x: 2,  word: "", icon: "", emoji: "" },
        { y: 3, x: 3,  word: "", icon: "", emoji: "" },
        { y: 3, x: 4,  word: "anyone", icon: "", emoji: "🤩" },
        { y: 3, x: 5,  word: "anyhow", icon: "", emoji: "🤩" },
        { y: 3, x: 6,  word: "", icon: "", emoji: "" },
        { y: 3, x: 7,  word: "", icon: "", emoji: "" },
        { y: 3, x: 8,  word: "", icon: "", emoji: "" },
        { y: 3, x: 9,  word: "anymore", icon: "", emoji: "🤩" },
        { y: 3, x: 10, word: "", icon: "", emoji: "" },
        { y: 3, x: 11, word: "", icon: "", emoji: "" },
        { y: 4, x: 0,  word: "", icon: "", emoji: "" },
        { y: 4, x: 1,  word: "", icon: "", emoji: "" },
        { y: 4, x: 2,  word: "", icon: "", emoji: "" },
        { y: 4, x: 3,  word: "grow", icon: "", emoji: "🤩", bg: colors.green },
        { y: 4, x: 4,  word: "bite", icon: "", emoji: "🤩", bg: colors.green },
        { y: 4, x: 5,  word: "anytime", icon: "", emoji: "🤩" },
        { y: 4, x: 6,  word: "chew", icon: "", emoji: "🤩", bg: colors.green },
        { y: 4, x: 7,  word: "", icon: "", emoji: "" },
        { y: 4, x: 8,  word: "", icon: "", emoji: "" },
        { y: 4, x: 9,  word: "smell", icon: "", emoji: "🤩", bg: colors.green },
        { y: 4, x: 10, word: "", icon: "", emoji: "" },
        { y: 4, x: 11, word: "anybody", icon: "", emoji: "🤩" },
        { y: 5, x: 0,  word: "", icon: "", emoji: "" },
        { y: 5, x: 1,  word: "", icon: "", emoji: "" },
        { y: 5, x: 2,  word: "", icon: "", emoji: "" },
        { y: 5, x: 3,  word: "", icon: "", emoji: "" },
        { y: 5, x: 4,  word: "", icon: "", emoji: "" },
        { y: 5, x: 5,  word: "anyway", icon: "", emoji: "🤩" },
        { y: 5, x: 6,  word: "", icon: "", emoji: "" },
        { y: 5, x: 7,  word: "", icon: "", emoji: "" },
        { y: 5, x: 8,  word: "feed", icon: "", emoji: "🤩", bg: colors.green },
        { y: 5, x: 9,  word: "", icon: "", emoji: "" },
        { y: 5, x: 10, word: "anything", icon: "", emoji: "🤩" },
        { y: 5, x: 11, word: "", icon: "", emoji: "" },
        // { y: 6, x: 0, clear }, is a constant
        { y: 6, x: 1,  word: "", icon: "", emoji: "" },
        { y: 6, x: 2,  word: "", icon: "", emoji: "" },
        { y: 6, x: 3,  word: "", icon: "", emoji: "" },
        { y: 6, x: 4,  word: "", icon: "", emoji: "" },
        { y: 6, x: 5,  word: "", icon: "", emoji: "" },
        { y: 6, x: 6,  word: "", icon: "", emoji: "" },
        { y: 6, x: 7,  word: "", icon: "", emoji: "" },
        { y: 6, x: 8,  word: "", icon: "", emoji: "" },
        { y: 6, x: 9,  word: "", icon: "", emoji: ""  },
        { y: 6, x: 10, word: "taste", icon: "", emoji: "🤩", bg: colors.green },
        { y: 6, x: 11, word: "", icon: "", emoji: "" }
    ]
};
